### ISSUE TITLE
Review CSS dependencies and core architecture

### ISSUE THREAD

**Issue by chrisburnell** [codezeus/django-react-blog#14]
### What dependencies/vendors do we have in our CSS?

0. [Normalize](http://necolas.github.io/normalize.css/)
0. [Include Media Mixin](http://include-media.com/)
0. [Bootstrap](http://getbootstrap.com/)

### Do we need Bootstrap?

In my experience, Bootstrap is a fantastic tool for prototyping and throwing up some content/data quickly, and can be extremely helpful in situations where you want expressive design without giving Editors a headache.

In most other situations, though, it ends up being a bloat to your CSS codebase, and in most cases, only a small fraction of the *Bootstrap* codebase is utilised. I find it to be an easier task to build the grid you need *~from-scratch* than to shim *Bootstrap* into doing what you want it to.

### What's required for our own grid system?

Not much. The first question to ask is, "What are our browser requirements?" This is an important question because it will influence a lot of CSS development decisions. Being that the grid is the foundation for the framework as a whole, it's important to choose a technique, or series of techniques, in order to remain consistent throughout.

For example, if we're able to [support Flexbox](http://caniuse.com/#search=flexbox) then we can define our grid in a very abstract way, and even removes some limitations from older-style grid systems: static column widths (whether `px`, `em`, `%`, etc.), static column gutters, static row widths, etc. If we're not able, we'll still be afforded a lot of customisation with a percentage-based grid.

But it is good practice to pick a row width, column width, gutter width, etc., so that is the next step. These should be defined as `$variables` in our SASS and called wherever necessary.

More to follow.

**Comment by dansackett** [comment]
I typically use Bootstrap as my defacto because I don't know much about grids and custom CSS systems. If we can remove Bootstrap then that would be great. I would love eliminating dependencies like that for more control in a custom system.

Note that if we remove Bootstrap, we can remove jQuery as well. I only included it because Bootstrap depends on it. Removing both would be a great performance gain for sure.

**Comment by chrisburnell** [comment]
I would love to remove *jQuery* as well. I'll start a basic grid for you to use and swap out *Bootstrap*.

**Comment by dansackett** [comment]
In the same idea, unless you need anything external from Bower I'm OK with removing bower completely to avoid that layer and simply use a CDN for fontawesome or get it through NPM.

**Comment by chrisburnell** [comment]
I typically try not to rely on any dependencies, or as few as possible. You can probably remove anything you personally won't use. I may like some gulp plugins at some point down the line, but I need to get my head around the codebase outside of the CSS first.

I don't need anything from Bower at least. :smiley:

And I'd even tend to steer away from fontawesome unless you know you'd use a lot of variation, or know you'd like the availability. Here's what I do:

included just after `<body>` –
[body-svg.html](https://raw.githubusercontent.com/chrisburnell/chrisburnell.github.io/master/_includes/body-svg.html)

in use –
[header.html](https://github.com/chrisburnell/chrisburnell.github.io/blob/master/_includes/header.html#L39)

Just ideas.

**Comment by chrisburnell** [comment]
Another option for FontAwesome is to selectively choose the glyphs we want based on the content... if that's not too heavy to do.

**Comment by dansackett** [comment]
I have found fontawesome to be the most comprehensive list and easiest to use but again, I'll leave this in your realm as we won't need that many glyphs. I'll remove Bower in this case and let's go from there.

**Comment by chrisburnell** [comment]
I think this is in a solid-enough state that we (@DanSackett) can call it resolved, provided we can find an agreement on the following remaining tangents of this discussion:

0. [FontAwesome](http://fontawesome.io/)? or [inline SVGs](https://github.com/chrisburnell/chrisburnell.github.io/blob/master/_includes/body-svg.html)?
  - My vote goes for inline SVGs.
0. Just a confirmation once again—are we cool with rolling with a Flexbox-based grid [based on the browser stats](caniuse.com/#search=flexbox)?
  - My vote is yes.

The other already-resolved pieces:

0. Bower - deprecated in #18
0. Bootstrap - deprecated in 0af24fbd89ed3cd74015c4de1a57cde975ba32bb

**Comment by dansackett** [comment]
Let's go with what you feel most comfortable with. I've never worked with SVGs but in the spirit of over-engineering I like the idea of it :)

As for flexbox, 100% support the decision. I haven't made IE users happy in at least 5 years.

Closing this issue.
